# Generated by Django 3.2.9 on 2021-11-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('author', models.CharField(max_length=50)),
                ('pub_date', models.DateField()),
                ('body', models.TextField()),
                ('notice_image', models.ImageField(blank=True, null=True, upload_to='notice/')),
            ],
        ),
    ]
