# Generated by Django 3.2.9 on 2021-11-18 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='St_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stc_content', models.CharField(max_length=2000)),
                ('Stc_author', models.CharField(max_length=50)),
                ('Stc_time', models.DateTimeField(auto_now=True)),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.notice')),
            ],
        ),
        migrations.CreateModel(
            name='No_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Noc_content', models.CharField(max_length=2000)),
                ('Noc_author', models.CharField(max_length=50)),
                ('Noc_time', models.DateTimeField(auto_now=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.notice')),
            ],
        ),
        migrations.CreateModel(
            name='Ma_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mac_content', models.CharField(max_length=2000)),
                ('Mac_author', models.CharField(max_length=50)),
                ('Mac_time', models.DateTimeField(auto_now=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.notice')),
            ],
        ),
        migrations.CreateModel(
            name='Gr_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grc_content', models.CharField(max_length=2000)),
                ('Grc_author', models.CharField(max_length=50)),
                ('Grc_time', models.DateTimeField(auto_now=True)),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.notice')),
            ],
        ),
        migrations.CreateModel(
            name='Fr_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Frc_content', models.CharField(max_length=2000)),
                ('Frc_author', models.CharField(max_length=50)),
                ('Frc_time', models.DateTimeField(auto_now=True)),
                ('free', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.notice')),
            ],
        ),
        migrations.CreateModel(
            name='Co_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Coc_content', models.CharField(max_length=2000)),
                ('Coc_author', models.CharField(max_length=50)),
                ('Coc_time', models.DateTimeField(auto_now=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.notice')),
            ],
        ),
        migrations.CreateModel(
            name='Cl_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Clc_content', models.CharField(max_length=2000)),
                ('Clc_author', models.CharField(max_length=50)),
                ('Clc_time', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.notice')),
            ],
        ),
    ]
