# Generated by Django 3.2.9 on 2021-11-18 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_cl_comment_co_comment_fr_comment_gr_comment_ma_comment_no_comment_st_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='no_comment',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='school.notice'),
        ),
    ]
