# Generated by Django 3.2.9 on 2021-11-18 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_no_comment_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_content', models.CharField(max_length=500)),
                ('notice_author', models.CharField(max_length=50)),
                ('notice_at', models.DateTimeField(auto_now=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='school.notice')),
            ],
        ),
        migrations.RemoveField(
            model_name='co_comment',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='fr_comment',
            name='free',
        ),
        migrations.RemoveField(
            model_name='gr_comment',
            name='graduate',
        ),
        migrations.RemoveField(
            model_name='ma_comment',
            name='market',
        ),
        migrations.RemoveField(
            model_name='no_comment',
            name='notice',
        ),
        migrations.RemoveField(
            model_name='st_comment',
            name='study',
        ),
        migrations.DeleteModel(
            name='Cl_comment',
        ),
        migrations.DeleteModel(
            name='Co_comment',
        ),
        migrations.DeleteModel(
            name='Fr_comment',
        ),
        migrations.DeleteModel(
            name='Gr_comment',
        ),
        migrations.DeleteModel(
            name='Ma_comment',
        ),
        migrations.DeleteModel(
            name='No_comment',
        ),
        migrations.DeleteModel(
            name='St_comment',
        ),
    ]
